version: "3.8"
services:
  db:
    build:
      context: "."
      dockerfile: docker/Dockerfile.db
    volumes:
      - ./docker/mysql:/var/lib/mysql
    env_file:
      - ${ENV_FILE_LOCATION}
    ports:
      - 3306:3306
    command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
    cap_add:
      - SYS_NICE

  uwsgi:
    restart: always
    build:
      context: "."
      dockerfile: docker/Dockerfile
#    command: tail -f /dev/null
    depends_on:
      - db
    environment:
      - COMMUNITY_NAME=${COMMUNITY_NAME}
      - RAILS_ENV=${RAILS_ENV}
      - CONFIRMABLE_ALLOWED_ACCESS_DAYS=${CONFIRMABLE_ALLOWED_ACCESS_DAYS}
      - LOCAL_DEV_PORT=${LOCAL_DEV_PORT}
    env_file:
      - ${ENV_FILE_LOCATION}
    ports:
      - "${LOCAL_DEV_PORT}:3000"
      # Ports required for debugging
      - "1234:1234"
      - "26166:26168"
    volumes:
      - .:/code
#      - ./static:/var/www/static
#      - ./images:/var/www/images
    links:
      - redis
      - db

  redis:
    restart: always
    image: redis:latest
    depends_on:
      - db
    ports:
      - 6379:6379
